baseURL = 'https://blog.ricardorompar.com'
languageCode = 'en-us'
theme = "dream"
title = "Ricardorompar's blog"
defaultContentLanguage = "en"

[params]
# zenMode = true
headerTitle = "Ricardorompar's blog"
motto = "A universe of atoms, an atom in the universe."
description = "A documented expression of thoughts and things I learn."

lightTheme = "emerald"
darkTheme = "business"
# Author
author = "Ricardo Romero"
email = "r2@ricardorompar.com"

#Footer
footerBottomText = "Built with ♥ using <a href='https://gohugo.io/' target='_blank'>Hugo</a> and the <a href='https://github.com/g1eny0ung/hugo-theme-dream' target='_blank'>Dream</a> theme."

siteStartYear = 2025

stickyNav = true
reorderNavItems = ["about", "search", "github", "posts", "categories", "tags"]
collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true

avatar = "img/lego_avatar_r2.png"
favicon = "img/favicon.ico"

[params.social]
twitter = "ricardorompar"
github = "ricardorompar"
linkedin = "ricardorompar"

[params.navItems]
github = { href = "https://github.com/ricardorompar", target = "_blank", icon = "logo-github", title = "GitHub" }

[markup]
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]
[markup.highlight]
noClasses = false